jasypt:
   encryptor:
      password: ${jasyptpwd:secretkey}
      algorithm: PBEWithMD5AndDES

server:
   port: 8083
   servlet:
      context-path: /microservicio-rentar
      session:
         timeout: 21600s

spring:
   datasource:
      driver-class-name: com.cj.jdbc.Driver
      type: com.zaxxer.hikari.HikariDataSource
      jdbcUrl: jdbc:mysql://localhost:3306/autorenting
      username: sergio
      password: 
      hikari:
         poolName: pool
